name: Deploy Docs

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install mkdocs
        run: pip install mkdocs
      - name: Deploy docs to GitHub page
        run: |
          mkdocs gh-deploy --force --clean --verbose
